class AccountNotFoundError(Exception):
    pass

class CheckError(Exception):
    pass
